//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by HisiSdkTest.rc
//
#define IDD_HISISDKTEST_DIALOG          102
#define IDR_MAINFRAME                   128
#define IDC_STA_INITIALIZE              1000
#define IDC_EDIT_ESEEID                 1001
#define IDC_STA_ESEEID                  1002
#define IDC_BTN_INITIALIZE              1003
#define IDC_BTN_CLEAR                   1004
#define IDC_EDIT_LOG                    1005
#define IDC_BTN_GETVERSION              1006
#define IDC_EDIT_VERSION                1007
#define IDC_STA_INITIALIZE2             1008
#define IDC_STA_IP                      1009
#define IDC_IPADDRESS1                  1010
#define IDC_STA_DVRPORT                 1011
#define IDC_STA_HTTPPORT                1012
#define IDC_EDIT_DVRPORT                1013
#define IDC_EDIT_HTTPPROT               1014
#define IDC_BTN_LOGIN                   1015
#define IDC_BTN_LOGOUT                  1016
#define IDC_BTN_GETINFO                 1017
#define IDC_STA_PREVIEW                 1018
#define IDC_EDIT_CHANNEL                1019
#define IDC_BTN_STARTREALPLAY           1020
#define IDC_BTN_STOPREALPLAY2           1021
#define IDC_STA_PLAYWND                 1022
#define IDC_STA_PLAKBACKWND             1023
#define IDC_BTN_SAVEREALDATA            1024
#define IDC_BTN_STOPSAVE                1025
#define IDC_BTN_CAPTURE                 1026
#define IDC_STA_PLAYBACK                1027
#define IDC_BTN_STARTPLAYBACK           1028
#define IDC_BTN_STOPPLAYBACK            1029
#define IDC_DTP_DATE                    1030
#define IDC_DTP_STARTTIME               1031
#define IDC_DTP_STOPTIME                1032
#define IDC_STA_DATE                    1033
#define IDC_STA_STARTTIME               1034
#define IDC_STA_STOPTIME2               1035
#define IDC_BTN_PAUSE                   1036
#define IDC_BTN_RESUME                  1037
#define IDC_BTN_PLAYBACKSAVE            1038
#define IDC_BTN_STOPPLAYBACKSAVE2       1039
#define IDC_BTN_GETFILEBYTIME           1040
#define IDC_BTN_STOPGETFILE             1041
#define IDC_BTN_PLAYBACKCAPTURE         1042
#define IDC_STA_FIND                    1043
#define IDC_BTN_FINDFILE                1044
#define IDC_BTN_FINDNEXT                1045
#define IDC_BTN_CLOSEFIND               1046
#define IDC_EDIT_FIND                   1047
#define IDC_STA_PLAKBACKWND2            1047
#define IDC_STA_PLAYFILE                1048
#define IDC_BTN_PLAY_INIT               1049
#define IDC_BTN_PLAY_RELEASE            1050
#define IDC_BTN_PLAY_OPEN               1051
#define IDC_BTN_PLAY_CLOSE              1052
#define IDC_BTN_PLAY_PLAY               1053
#define IDC_STA_PLAYFILEWND             1054
#define IDC_BTN_PLAY_STOP               1055
#define IDC_BTN_PLAY_PAUSE              1056
#define IDC_BTN_PLAY_RESUME             1057
#define IDC_STA_PLAYFILECONTROL         1058
#define IDC_BTN_PLAY_GETPOS             1059
#define IDC_BTN_FAST                    1060
#define IDC_BTN_SLOW                    1061
#define IDC_BTN_PLAY_SETPOS             1062
#define IDC_BTN_PTZ                     1063
#define IDC_COMBO_PTZ                   1064
#define IDC_BTN_GETPORT                 1065
#define IDC_BTN_FREEPORT                1066
#define IDC_EDIT_FREEPORT               1067
#define IDC_BTN_PLAYCAPTURE             1068
#define IDC_BTN_GETCONFIG               1069
#define IDC_BTN_PLAY_GETTIME            1070
#define IDC_BTN_PLAY_GETPLAYTIME        1071
#define IDC_CHK_OPENSOUND               1072
#define IDC_STA_BROADCAST               1073
#define IDC_BTN_BRDC_START              1074
#define IDC_BTN_BRDC_ADD                1075
#define IDC_BTN_BRDC_DEL                1076
#define IDC_BTN_BRDC_STOP               1077
#define IDC_IP_BRDC                     1078
#define IDC_EDIT_BRDC_PORT              1079
#define IDC_BTN_CLEARLOG                1080
#define IDC_BTN_STREAM_OPEN             1081
#define IDC_BTN_STREAM_INPUT            1082
#define IDC_BTN_STREAM_OPEN3            1083
#define IDC_BTN_STREAM_CLOSE            1083
#define IDC_CHECK1                      1084
#define IDC_CHECK_ALARM                 1084
#define IDC_IP_ALARM                    1085
#define IDC_EDIT_ALARM_PORT             1086
#define IDC_STA_ALARM_USRNAME           1087
#define IDC_STA_HTTPPORT2               1088
#define IDC_EDIT_ALARM_USRNAME          1089
#define IDC_EDIT_ALARM_PASSWD           1090
#define IDC_LIST_FINDFILE               1091
#define IDC_BUTTON1                     1092
#define IDC_BUTTON_PLAYBYNAME           1092
#define IDC_BUTTON2                     1093
#define IDC_BTN_GETFILEBYNAME           1093
#define IDC_BUTTON3                     1094
#define IDC_BUTTON_GETFILEPOS           1094
#define IDC_BUTTON_PLAYBYNAME2          1095
#define IDC_BTN_STOPPLAYBACK2           1096
#define IDC_BTN_GETFILEBYNAME2          1097
#define IDC_BUTTON4                     1098
#define IDC_BUTTON_STEP                 1098
#define IDC_BUTTON_GETPLAYPOS           1099
#define IDC_BUTTON_GETPLAYPOS2          1100
#define IDC_EDIT1                       1101

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1102
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
